name: AI PR Review

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: false

      - name: Checkout AI reviewer tools
        uses: actions/checkout@v3
        with:
          repository: AbigailF1/Ai-PR-reviewer
          path: tools

      - name: Install dependency
        run: pip install requests

      - name: Debug secrets
        shell: bash
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY is not set"
          else
            echo "GEMINI_API_KEY is set"
          fi

      - name: Run AI reviewer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        run: python tools/scripts/call_gemini.py
